### ISSUE TITLE
Add a basics file

### ISSUE THREAD

**Issue by johanni2000** [MaxHTu/GeneticAlgorithm.jl#9]
Add a file that includes the basic functionalities used for the tasks (crossover, mutation,...) that are necessary for each implementation. Or add to main. 

Just to avoid conflicts when merging and making sure those basic functionalities are working.
Maybe it is even possible to include a fitness function that is more general and can be specified for different tasks with new parameters?

**Comment by johanni2000** [comment]
If none of this makes sense, just ignore it :)

**Comment by SimonovKirill** [comment]
Added separate files for every modular part of the package.
